name: Run Selemiun Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  selemiun-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install selenium-side-runner and chromedriver
        run: |
          npm install -g selenium-side-runner chromedriver

      - name: Run Selenium IDE tests
        run: |
          selenium-side-runner -c '{"browserName":"chrome","goog:chromeOptions":{"args":["--headless","--no-sandbox","--disable-dev-shm-usage"]}}' selenium/ItemManager.side
